[package]
name = "kernel"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic_enum = "0.2.0"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
log = "0.4"
raw-cpuid = "10.6.0"
x86_64 = "0.14.10"
x86 = "0.52.0"
